package com.example.backend.cases;

public enum EventType {
  CASE_CREATED,
  NOTE_ADDED,
  STATUS_CHANGED,
  TITLE_CHANGED,
  NOTE_UPDATED,
  NOTE_DELETED,
  SUMMARY_DRAFT_CREATED,
  SUMMARY_ACCEPTED,
  SUMMARY_REJECTED,
}
